red:
  - name: "Default Creature"
    pattern: "%w+"
    priority: 1000
  - name: "Default NPC"
    pattern: "%w+"
    is_creature: false
    priority: 1000
blue:
  - name: "Crab"
    pattern: "crab"
  - name: "Dreugh"
    pattern: "dreugh"
ectoplasm:
  - name: "Ghost"
    pattern: "ghost"
  - name: "Wraith"
    pattern: "wraith"
green:
  - name: "Kwama"
    pattern: "[kK]wama"
  - name: "Scrib"
    pattern: "[sS]crib"
  - name: "Netch"
    pattern: "[nN]etch"
  - name: "Nix-Hound"
    pattern: "nix%-hound"
oil:
  - name: "Dwemer Construct"
    pattern: "[cC]enturion"
dust:
  - name: "Skeleton"
    pattern: "[sS]keleton"
  - name: "Bonewalker"
    pattern: "[bB]onewalker"
