humanoid:
  - name: "Humanoid NPCs"
    pattern: "%w+"
    is_creature: false
insect:
  - name: "Kwama"
    pattern: "[kK]wama"
  - name: "Scrib"
    pattern: "[sS]crib"
machine:
  - name: "Dwemer Constructs"
    pattern: "[cC]enturion"
undead:
  - name: "Skeleton"
    pattern: "[sS]keleton"
  - name: "Zombie"
    pattern: "[zZ]ombie"
  - name: "Bonewalker"
    pattern: "[bB]onewalker"
