red:
  - name: "Default Creatures"
    pattern: "%w+"
    priority: 1000
  - name: "Default NPCs"
    pattern: "%w+"
    is_creature: false
    priority: 1000
blue:
  - name: "Crabs"
    pattern: "crab"
  - name: "Dreugh"
    pattern: "dreugh"
ectoplasm:
  - name: "Ghosts"
    pattern: "ghost"
  - name: "Wraiths"
    pattern: "wraith"
green:
  - name: "Kwama"
    pattern: "[kK]wama"
  - name: "Scrib"
    pattern: "[sS]crib"
  - name: "Netch"
    pattern: "[nN]etch"
oil:
  - name: "Dwemer Constructs"
    pattern: "[cC]enturion"
dust:
  - name: "Skeleton"
    pattern: "[sS]keleton"
  - name: "Bonewalker"
    pattern: "[bB]onewalker"
